model:
  #name: MSRP.decompose.GloVe.200d.Adam
  class_num: 2
  project_dim: 200
  #intra_attention: True

data:
  name: MSRP
  embedding: GloVe
  preproc: Tokenize

train:
  epoch_num: 300
  batch_size: 512
  keep_prob: 0.5
