model:
  model_type: AttentiveModel
  class_num: 3
  bias_init: 0.01

data:
  name: SNLI
  embedding: GloVeNorm
  seed: 6523

train:
  restore_from: 'SNLI.GloVeNorm.Adagrad.att'
  restore_step: 700000
  train_regex_list:
    - 'aggregate/*'
  learning_rate: 0.5
  epoch_num: 100
  batch_size: 64
  keep_prob: 0.8
  seed: 1234
