model:
  model_type: CAFE
  class_num: 3

data:
  name: SNLI
  embedding: GloVeNorm
  seed: 6523

train:
  data:
    cache: True
    argument: False
  epoch_num: 100
  batch_size: 16
  keep_prob: 0.8
  seed: 1234
  record_every: 200
  validate_every: 2000
  save_every: 20000
  optim_manager:
    type: NotChange
  optim:
    optim_type: AdamOptimizer
    learning_rate: 0.0003
