model:
  model_type: SyntacticForwardAttV2
  class_num: 3
  bias_init: 0.01

data:
  name: SNLI
  embedding: GloVeNorm
  seed: 6523

train:
  epoch_num: 20
  batch_size: 64
  learning_rate: 0.05
  keep_prob: 0.8
  seed: 1234
