model:
  model_type: AttentiveModel
  class_num: 3
  bias_init: 0.01
  use_lstm: True

data:
  name: SNLI
  embedding: GloVeNorm
  seed: 6523

train:
  epoch_num: 100
  batch_size: 64
  keep_prob: 0.8
  seed: 1234
