model:
  model_type: SyntacticForwardAtt
  class_num: 3
  bias_init: 0.01

data:
  name: SNLI
  embedding: GloVeNorm
  seed: 6523

train:
  restore_from: 'SNLI.GloVeNorm.Adagrad.syn'
  restore_step: 171679  # 20 epoches
  epoch_num: 80
  batch_size: 64
  learning_rate: 0.05
  keep_prob: 0.8
  seed: 1234
