model:
  model_type: ESIM
  class_num: 3

data:
  name: SNLI
  embedding: GloVeNorm
  seed: 6523

train:
  data:
    cache: False
    argument: False
  epoch_num: 100
  batch_size: 128
  keep_prob: 0.5
  #keep_prob: 0.8
  clip_norm: 10
  seed: 1234
  optim_manager:
    type: NotChange
  optim:
    optim_type: AdamOptimizer
    learning_rate: 0.001
