# train: 88.30
# test:  79.18


model:
  class_num: 3
  intra_attention: True

data:
  name: SNLI
  preproc: Tokenize
  embedding: Word2Vec

train:
  validate: False
  epoch_num: 100
  batch_size: 64
  keep_prob: 0.8
