model:
  model_type: AttentiveModel
  class_num: 3
  bias_init: 0.01

data:
  name: SNLI
  embedding: GloVeNorm
  seed: 6523

train:
  optimizer_type: AdamOptimizer
  learning_rate: 0.00005
  data_cache: True
  epoch_num: 100
  batch_size: 64
  keep_prob: 0.8
  seed: 1234
