model:
  model_type: SyntacticForwardAttV6
  class_num: 3
  bias_init: 0.01

data:
  name: SNLI
  embedding: GloVeNorm
  seed: 6523

train:
  optimizer_type: AdamOptimizer
  learning_rate: 0.001
  epoch_num: 1000
  batch_size: 1024
  record_every: 25
  validate_every: 250
  save_every: 10000
  keep_prob: 0.8
  seed: 1234
